name: ilm

secrets:
  trusted_certificates.pem:
    file: ./secrets/trusted_certificates.pem

services:
  opa:
    container_name: opa
    image: openpolicyagent/opa:1.10.0-static
    restart: unless-stopped
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--set=services.nginx.url=http://opa-bundles:8080"
      - "--set=bundles.nginx.service=nginx"
      - "--set=bundles.nginx.resource=bundles/bundle.tar.gz"
    depends_on:
      - opa-bundle-server
    profiles:
      - opa-standalone
      - core-dev
      - core
      - all

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2.0-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
      - ./data/rabbitmq/logs:/var/log/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - rabbitmq-standalone
      - core-dev
      - core
      - all

  auth:
    container_name: auth
    image: ilm-auth
    build: ${ILM_SOURCES_BASE_DIR}/auth
    restart: unless-stopped
    ports:
      - 8100:8080
    secrets:
      - trusted_certificates.pem
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AUTH_DB_CONNECTION_STRING=Host=${DB_HOST};Port=${DB_PORT};Username=${DB_USERNAME};Password=${DB_PASSWORD};Database=${DB_NAME};Pooling=true
      - AUTH_CREATE_UNKNOWN_USERS=true
      - AUTH_CREATE_UNKNOWN_ROLES=true
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./secrets/trusted_certificates.pem:/etc/ssl/certs/trusted_certificates.pem
    healthcheck:
      test: wget -O - http://localhost:8080/health | grep -q 'Healthy'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - auth-standalone
      - core-dev
      - core
      - all

  opa-bundle-server:
    container_name: opa-bundles
    image: ilm-opa-bundles
    build: ${ILM_SOURCES_BASE_DIR}/auth-opa-policies
    restart: unless-stopped
    ports:
      - 8101:8080
    profiles:
      - opa-bundle-server-standalone
      - core-dev
      - core
      - all

  scheduler:
    container_name: scheduler
    image: ilm-scheduler
    build: ${ILM_SOURCES_BASE_DIR}/scheduler
    restart: unless-stopped
    ports:
      - 8102:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
      - BROKER_URL=amqp://rabbitmq:5672
      - BROKER_USERNAME=guest
      - BROKER_PASSWORD=guest
      - BROKER_VIRTUAL_HOST=
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - scheduler-standalone
      - core-dev
      - core
      - all

  utils:
    container_name: utils
    image: ilm-utils
    build: ${ILM_SOURCES_BASE_DIR}/utils-service
    restart: unless-stopped
    ports:
      - 8110:8080
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - all
      - utils

  core:
    container_name: core
    image: hub.omnitrustregistry.com/ilm/core:develop-latest
    #    image: ilm-core
    #    build: ${ILM_SOURCES_BASE_DIR}/core
    restart: unless-stopped
    ports:
      - 8280:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
      - OPA_BASE_URL=http://opa:8181
      - AUTH_SERVICE_BASE_URL=http://auth:8080
      - SCHEDULER_BASE_URL=http://scheduler:8080
      - BROKER_URL=amqp://rabbitmq:5672
      - BROKER_USERNAME=guest
      - BROKER_PASSWORD=guest
      - BROKER_VIRTUAL_HOST=
      - LOGGING_LEVEL_COM_OTILM=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:8080/api/v1/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - core-standalone
      - core
      - all

  common-credential-provider:
    container_name: common-credential-provider
    image: ilm-common-credential-provider
    build: ${ILM_SOURCES_BASE_DIR}/common-credential-provider
    restart: unless-stopped
    ports:
      - 8200:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/v2/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - common-credential-provider-standalone
      - all

  ejbca-ng-connector:
    container_name: ejbca-ng-connector
    image: ilm-ejbca-ng-connector
    build:
      context: ${ILM_SOURCES_BASE_DIR}/ejbca-ng-connector
      args:
        - SERVER_USERNAME=${GITHUB_USERNAME}
        - SERVER_PASSWORD=${GITHUB_PASSWORD}
    restart: unless-stopped
    ports:
      - 8210:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - ejbca-ng-connector-standalone
      - all

  pyadcs-connector:
    container_name: pyadcs-connector
    image: ilm-pyadcs-connector
    build: ${ILM_SOURCES_BASE_DIR}/pyadcs-connector
    restart: unless-stopped
    ports:
      - 8211:8080
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_SCHEMA=pyadcs
    profiles:
      - pyadcs-connector-standalone
      - all

  hashicorp-vault-connector:
    container_name: hashicorp-vault-connector
    image: ilm-hashicorp-vault-connector
    build: ${ILM_SOURCES_BASE_DIR}/hashicorp-vault-connector
    restart: unless-stopped
    ports:
      - 8212:8080
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/v1/health | grep -q '{"status":"ok"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - hashicorp-vault-connector-standalone
      - all

  external-authority-provider:
    container_name: external-authority-provider
    image: ilm-external-authority-provider
    build: ${ILM_SOURCES_BASE_DIR}/external-authority-provider
    restart: unless-stopped
    ports:
      - 8213:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - external-authority-provider-standalone
      - all

  # ejbca-legacy-connector:
  #   container_name: ejbca-legacy-connector
  #   image: ilm-ejbca-legacy-connector
  #   build: ${ILM_SOURCES_BASE_DIR}/ejbca-legacy-ca-connector
  #   ports:
  #       - 8211:8080
  #   environment:
  #     - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
  #     - JDBC_USERNAME=${DB_USERNAME}
  #     - JDBC_PASSWORD=${DB_PASSWORD}
  #     - SERVER_USERNAME=${GITHUB_USERNAME}
  #     - SERVER_PASSWORD=${GITHUB_PASSWORD}
  #   profiles:
  #     - ejbca-legacy-connector-standalone
  #     - all

  keystore-entity-provider:
    container_name: keystore-entity-provider
    image: ilm-keystore-entity-provider
    build: ${ILM_SOURCES_BASE_DIR}/keystore-entity-provider
    restart: unless-stopped
    ports:
      - 8220:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - keystore-entity-provider-standalone
      - all

  software-cryptography-provider:
    container_name: software-cryptography-provider
    image: ilm-software-cryptography-provider
    build: ${ILM_SOURCES_BASE_DIR}/software-cryptography-provider
    restart: unless-stopped
    ports:
      - 8230:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - software-cryptography-provider-standalone
      - all

  ip-discovery-provider:
    container_name: ip-discovery-provider
    image: ilm-ip-discovery-provider
    build: ${ILM_SOURCES_BASE_DIR}/ip-discovery-provider
    restart: unless-stopped
    ports:
      - 8240:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - ip-discovery-provider-standalone
      - all

  cryptosense-discovery-provider:
    container_name: cryptosense-discovery-provider
    image: ilm-cryptosense-discovery-provider
    build: ${ILM_SOURCES_BASE_DIR}/cryptosense-discovery-provider
    ports:
      - 8241:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - cryptosense-discovery-provider-standalone
      - all

  ct-logs-discovery-provider:
    container_name: ct-logs-discovery-provider
    image: ilm-ct-logs-discovery-provider
    build: ${ILM_SOURCES_BASE_DIR}/ct-logs-discovery-provider
    restart: unless-stopped
    ports:
      - 8242:8080
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/v1/health | grep -q '{"status":"ok"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - ct-logs-discovery-provider-standalone
      - all

  x509-compliance-provider:
    container_name: x509-compliance-provider
    image: ilm-x509-compliance-provider
    build: ${ILM_SOURCES_BASE_DIR}/x509-compliance-provider
    restart: unless-stopped
    ports:
      - 8250:8080
    healthcheck:
      test: wget -O - http://localhost:8080/v1/health | grep -q '{"status":"ok"'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - x509-compliance-provider-standalone
      - all

  email-notification-provider:
    container_name: email-notification-provider
    image: ilm-email-notification-provider
    build: ${ILM_SOURCES_BASE_DIR}/email-notification-provider
    restart: unless-stopped
    ports:
      - 8260:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - email-notification-provider-standalone
      - all

  timestamp-signature-formatter:
    container_name: timestamp-signature-formatter
    image: ilm-timestamp-signature-formatter
    build:
      context: ${ILM_SOURCES_BASE_DIR}/timestamp-formatter-connector
    restart: unless-stopped
    ports:
      - 8270:8080
    healthcheck:
      test: wget -O - http://localhost:8080/v2/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - timestamp-signature-formatter-standalone
      - all

  webhook-notification-provider:
    container_name: webhook-notification-provider
    image: ilm-webhook-notification-provider
    build: ${ILM_SOURCES_BASE_DIR}/webhook-notification-provider
    restart: unless-stopped
    ports:
      - 8261:8080
    environment:
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
      - JDBC_USERNAME=${DB_USERNAME}
      - JDBC_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: wget -O - http://localhost:8080/health/liveness | grep -q '{"status":"UP"}'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - webhook-notification-provider-standalone
      - all

  interface-docs:
    container_name: interface-docs
    image: ilm-interface-docs
    build: ${ILM_SOURCES_BASE_DIR}/interface-documentation
    ports:
      - 8300:80
    profiles:
      - interface-docs-standalone
      - all

  ejbca:
    container_name: ejbca
    image: keyfactor/ejbca-ce:8.2.0.1
    restart: unless-stopped
    ports:
      - 8301:8080
      - 8302:8443
    environment:
      - TLS_SETUP_ENABLED=simple
    profiles:
      - ejbca-standalone
      - all

  time-quality-monitor:
    container_name: time-quality-monitor
    image: ilm-time-quality-monitor
    build:
      context: ${ILM_SOURCES_BASE_DIR}/time-quality-monitor
    restart: unless-stopped
    environment:
      - BROKER_URL=amqp://rabbitmq:5672
      - BROKER_USERNAME=guest
      - BROKER_PASSWORD=guest
      - BROKER_VIRTUAL_HOST=
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:8080/health | grep -E -q '^\{"status":"UP"'
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - time-quality-monitor-standalone
      - all

  ntp:
    container_name: ntp
    image: ilm-ntp
    build: ./ntp
    restart: unless-stopped
    cap_add:
      - SYS_TIME
    healthcheck:
      test: chronyc -n tracking
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - ntp-standalone
      - all
