name: czertainly

services:

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/postgres/pgsqldata:/var/lib/postgresql/data:delegated
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - database
      - all

  adminer:
    container_name: postgres-adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8088:8080
    profiles:
      - all
